### ISSUE TITLE
dylib error on Mac Silicon

### ISSUE THREAD

**Issue by jacob-lee** [stspec/pyspssio#9] opened 2024-08-22 15:02 UTC
I'm running in python 3.12.2 on a M1 Mac (so Apple Silicon). Installed pyspssio-0.4.4-py3-one-any.whl using pip install pyspssio. Not sure if you plan to support Apple Silicon, but just in case: when trying to open up a sav file, I got this error:

>>> df, meta = pyspssio.read_sav('W7.sav')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.12/site-packages/pyspssio/user_functions.py", line 135, in read_sav
    with Reader(
         ^^^^^^^
  File ".venv/lib/python3.12/site-packages/pyspssio/reader.py", line 46, in __init__
    super().__init__(*args, **kwargs)
  File ".venv/lib/python3.12/site-packages/pyspssio/header.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File ".venv/lib/python3.12/site-packages/pyspssio/spssfile.py", line 65, in __init__
    self.spssio = loader(config.spssio_module)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(.venv/lib/python3.12/site-packages/pyspssio/spssio/macos/libspssdio.dylib, 0x0006): tried: '.venv/lib/python3.12/site-packages/pyspssio/spssio/macos/libspssdio.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '.venv/lib/python3.12/site-packages/pyspssio/spssio/macos/libspssdio.dylib' (no such file), '.venv/lib/python3.12/site-packages/pyspssio/spssio/macos/libspssdio.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

**Comment by stspec** [comment] 2024-11-09 20:16
This seems to be a duplicate of https://github.com/stspec/pyspssio/issues/5

**Closed as not planned by stspec** 2024-11-09 20:16 UTC
