### ISSUE TITLE
pyspssio crashes in Ubuntu 22.04 

### ISSUE THREAD

**Issue by TheTallBlonde1** [stspec/pyspssio#4] opened 2023-08-02 14:26 UTC
I am running python 3.11.4 in a Ubuntu 22.04 dev container, when attempting to read a sav file python is crashing with no error message.

The first error I got was this: 
/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyspssio/spssfile.py:91: UserWarning: Failed to set locale to: en_US.UTF-8. Current locale is: en_US.UTF-8

I then set the locale information in Ubuntu an no longer got this message.  Instead I the whenever the script tries to get any attribute from the Reader (after line 49 in reader.py) (or even if I open the Reader obj in debug) the script crashes with no error message.

**Comment by stspec** [comment] 2023-08-03 02:24
I'm not able to reproduce this issue (also using a dev container with Ubuntu 22.04 and python 3.11.4).

Is this happening for a particular sav file or all sav files in your environment? Are you manually setting any parameters when reading the file? If you're able to provide the sav file or an example one created in the same way, that might help.

**Comment by stspec** [comment] 2023-08-10 18:01
Closing this issue pending further details.

Unlike other IO module functions, the `spssSetLocale` function returns a locale string instead of a return/error code. The pyspssio package currently assumes the IO module function failed in this case if it returns an empty string. There doesn't seem to be an easy way to tell why it may have failed. A user warning is indicated instead of an exception because even if the locale can't be set, the sav file may still be read/written correctly (ex. if the encodings are compatible).

**Closed as completed** 2023-08-10 21:21 UTC
